FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
            unzip \
            wget \
            python3-dev \
            python3-numpy \
	    python3-tk \
            python3-pip \
            python3-setuptools \
            ca-certificates \
            build-essential \
            gcc \
            make \
	    cmake \
            zlib1g \
            zlib1g-dev \
            libglib2.0 \
            libssl-dev \
    	    pkg-config \
    	    ffmpeg \ 
            qt4-default \
            libbz2-dev \
            libopencv-dev \
            libgtk-3-dev \
            libdc1394-22 \
            libdc1394-22-dev \ 
            libjpeg-dev \
            libpng12-dev \
            libtiff5-dev \
            libjasper-dev \
            libglew-dev \
            libboost-all-dev

RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev \
    libxine2-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev \
    libv4l-dev libtbb-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev \
    libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev v4l-utils vtk6 \
    liblapacke-dev libopenblas-dev libgdal-dev checkinstall


RUN pip3 install -U \
	cython \
	tqdm \
	pillow \
	shapely \
	pyyaml \
	tensorflow-gpu==1.10.0 \
	scipy \
	sklearn \
	pyzmq \
	redis 


#install opencv 
WORKDIR /
ENV OPENCV_VERSION="3.4.3"
RUN wget https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip \
&& unzip ${OPENCV_VERSION}.zip \
&& rm ${OPENCV_VERSION}.zip
RUN wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip \
&& unzip ${OPENCV_VERSION}.zip \
&& mkdir /opencv-${OPENCV_VERSION}/cmake_binary \
&& cd /opencv-${OPENCV_VERSION}/cmake_binary \
&& cmake -DBUILD_TIFF=ON \
  -DBUILD_opencv_java=OFF \
  -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib-${OPENCV_VERSION}/modules \
  -DWITH_CUDA=ON \
  -DENABLE_FAST_MATH=1 \
  -DCUDA_FAST_MATH=1 \
  -DWITH_CUBLAS=ON \
  -DWITH_OPENCL=ON \
  -DUSE_FAST_MATH=ON \
  -DWITH_QT=ON \
  -DENABLE_AVX=ON \
  -DWITH_OPENGL=ON \
  -DWITH_IPP=ON \
  -DWITH_FFMPEG=ON \
  -DWITH_TBB=ON \
  -DWITH_EIGEN=ON \
  -DWITH_V4L=ON \
  -DBUILD_TESTS=OFF \
  -DCUDA_NVCC_FLAGS="-D_FORCE_INLINES" \
  -DBUILD_PERF_TESTS=OFF \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DCMAKE_INSTALL_PREFIX=$(python3.5 -c "import sys; print(sys.prefix)") \
  -DPYTHON_EXECUTABLE=$(which python3.5) \
  -DPYTHON_INCLUDE_DIR=$(python3.5 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
  -DPYTHON_PACKAGES_PATH=$(python3.5 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") .. \
&& make -j32 install \
&& rm /${OPENCV_VERSION}.zip \
&& rm -r /opencv-${OPENCV_VERSION} 

RUN apt-get update --fix-missing && \
    apt-get install -y git \
		libboost-all-dev \
		libgflags-dev \
		libgoogle-glog-dev \
		libhdf5-serial-dev \
		libleveldb-dev \
		liblmdb-dev \
		libopencv-dev \
		libprotobuf-dev \
		libsnappy-dev \
		protobuf-compiler \
                libboost-python-dev \
                python-skimage \  
                python-protobuf \
		&& \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*
 

RUN pip3 install sk-video
RUN pip3 install python-dateutil

WORKDIR /src
ENV PYTHONPATH=$PYTHONPATH:/src/:/src/components

